apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-workload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-workload
  template:
    metadata:
      labels:
        app: example-workload
    spec:
      containers:
      - name: example-workload-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
